
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Metoda daActionPerformed actualizeaza Baza de Date daca utilizatorul alege sa cumpere produsul accesat
 * Metoda close inchide fereastra curenta
 * Metoda nuActionPerformed apeleaza metoda close() la accesarea butonului NU
 */

/**
 *
 * @author Ariana
 */
public class ExistWin extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst=null;
String ID;
String cant;
String tmp;
String nume,price,idp;
WindowEvent winClosingEvent;
String userId;
    /**
     * Creates new form ExistWin
     */
    public ExistWin() {
        initComponents();
        conn=JavaConnect.ConnectDB();    
    }
    
    public ExistWin(String ID,String cant,String idp,String userId){
        initComponents();
        conn=JavaConnect.ConnectDB(); 
        this.ID=ID;
        this.cant=cant;
        this.idp=idp;
        this.userId=userId;
    }

    public void close(){
        winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        da = new javax.swing.JButton();
        nu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Produsul comandat exista in depozit!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Doriti sa il achizitionati?");

        da.setText("DA");
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });

        nu.setText("NU");
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(da)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(da)
                    .addComponent(nu))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
       
        String sql1="Select * from Warehouse where ID=?";
     
        try{
            pst=conn.prepareStatement(sql1);
            pst.setString(1, ID);
            rs=pst.executeQuery();
            tmp=rs.getString("stoc");    
            nume=rs.getString("productName");
        }catch(Exception e){
            System.out.println(e);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
        String sql5="Select * from Product where ID=?";
          try{
            pst=conn.prepareStatement(sql5);
            pst.setString(1, idp);
            rs=pst.executeQuery();
            price=rs.getString("price");
            
        }catch(Exception e){
            System.out.println(e);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
            int cantitate=Integer.parseInt(tmp);
        
            int cantaux=Integer.parseInt(cant);
        if(cantaux<cantitate){
            cantitate=cantitate-cantaux;
       
        System.out.println(cantitate);
        String sql="UPDATE Warehouse set stoc='"+cantitate+"' where ID='"+ID+"'";
        try{
           pst=conn.prepareStatement(sql);
           pst.executeUpdate();
        }catch(Exception e){
            System.out.println(e);
         }finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
        String sql2="INSERT INTO Cos(productName,price,amount,status,userid) VALUES (?,?,?,?,?)";
        
        try{
           pst=conn.prepareStatement(sql2);
           pst.setString(1, nume);
           pst.setString(2, price);
           pst.setString(3, cant);
           pst.setString(4, "No status!");
           pst.setString(5, userId);
           
           pst.executeUpdate();
           
           
        }catch(Exception e){
            System.out.println(e);
        }finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
        else
            JOptionPane.showMessageDialog(null, "Nu avem cantitatea ceruta de dvs.!");
        
        close();
    }//GEN-LAST:event_daActionPerformed

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_nuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExistWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExistWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExistWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExistWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExistWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton da;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nu;
    // End of variables declaration//GEN-END:variables
}
